### ISSUE TITLE
mining.stop

### ISSUE THREAD

**Issue by jhihyiwu** [DecentricCorp/web3admin#2]
I download web3admin and use mining.stop, but the function doesn't work.
mining.start is OK, but mining.stop show err
"Error: too many arguments, want at most 0"
<img width="886" alt="螢幕快照 2019-08-20 上午10 41 56" src="https://user-images.githubusercontent.com/21351137/63313525-5ea4ff80-c337-11e9-86ad-984e81f3b0ae.png">

How to solve it?
Thanks!

**Comment by kuniaki** [comment]
This issue was solved?   I also run into same issue.   unable to stop mining.

The following is the error log.   

isMining? false
/Users/kuniaki/web3admin/node_modules/web3/lib/web3/requestmanager.js:61
        throw errors.InvalidResponse(result);
        ^

Error: too many arguments, want at most 0
    at Object.InvalidResponse (/Users/kuniaki/web3admin/node_modules/web3/lib/web3/errors.js:35:16)
    at RequestManager.send (/Users/kuniaki/web3admin/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Object.send [as stop] (/Users/kuniaki/web3admin/node_modules/web3/lib/web3/method.js:145:58)
    at Timeout._onTimeout (/Users/kuniaki/web3admin/index.js:25:50)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
